ERROR 2025-09-11 16:01:41,494 log 22508 19200 Internal Server Error: /api/accounts/login/
ERROR 2025-09-11 16:12:27,405 log 24316 23540 Internal Server Error: /payments/
Traceback (most recent call last):
  File "D:\Anaconda\envs\django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Anaconda\envs\django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\django_learning\keshe\payments\views.py", line 539, in payments_index
    return render(request, 'payments/index.html', {
  File "D:\Anaconda\envs\django\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anaconda\envs\django\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Anaconda\envs\django\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: payments/index.html
ERROR 2025-09-11 16:12:44,504 log 24316 2948 Internal Server Error: /payments/
Traceback (most recent call last):
  File "D:\Anaconda\envs\django\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Anaconda\envs\django\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\django_learning\keshe\payments\views.py", line 539, in payments_index
    return render(request, 'payments/index.html', {
  File "D:\Anaconda\envs\django\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anaconda\envs\django\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Anaconda\envs\django\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: payments/index.html
ERROR 2025-09-12 15:09:39,200 log 23440 19188 Internal Server Error: /api/competitions/
ERROR 2025-09-12 15:10:49,545 log 19032 9896 Internal Server Error: /api/competitions/
ERROR 2025-09-12 15:10:49,558 log 19032 9896 Internal Server Error: /api/competitions/3/
ERROR 2025-09-12 15:10:49,561 log 19032 9896 Internal Server Error: /api/competitions/3/
ERROR 2025-09-12 15:12:53,660 log 25012 19928 Internal Server Error: /api/competitions/7/register/
ERROR 2025-09-12 15:13:29,481 log 12772 10444 Internal Server Error: /api/competitions/9/register/
ERROR 2025-09-12 15:14:20,868 log 25348 21920 Internal Server Error: /api/competitions/11/register/
ERROR 2025-09-12 15:15:01,365 log 23016 21516 Internal Server Error: /api/competitions/15/registrations/
ERROR 2025-09-12 15:15:23,901 log 15484 23872 Internal Server Error: /api/competitions/17/registrations/
ERROR 2025-09-12 15:16:49,729 log 23940 21388 Internal Server Error: /api/competitions/19/matches/
ERROR 2025-09-12 15:17:01,771 log 23940 24720 Internal Server Error: /api/competitions/19/matches/
ERROR 2025-09-12 15:17:11,061 log 23940 24720 Internal Server Error: /api/competitions/18/matches/
ERROR 2025-09-12 15:21:46,241 log 19352 21476 Internal Server Error: /api/competitions/19/matches/
ERROR 2025-09-12 15:24:28,802 log 11016 18772 Internal Server Error: /api/competitions/19/matches/
ERROR 2025-09-12 16:04:35,639 log 18628 19688 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:04:36,028 log 18628 2716 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:04:36,419 log 18628 21800 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:04:36,808 log 18628 24388 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:04:37,199 log 18628 23864 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:04:37,588 log 18628 18740 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:05:12,894 log 18628 18440 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:05:13,306 log 18628 16956 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:05:13,691 log 18628 10940 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:05:14,075 log 18628 19756 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:05:14,459 log 18628 18752 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:05:14,843 log 18628 19616 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:05:15,229 log 18628 18192 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:05:15,614 log 18628 25396 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,760 log 22076 3172 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,764 log 22076 384 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,767 log 22076 25572 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,770 log 22076 14232 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,774 log 22076 12900 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,777 log 22076 17252 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,781 log 22076 24448 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,785 log 22076 15956 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,788 log 22076 24880 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,792 log 22076 25896 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,795 log 22076 19412 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,798 log 22076 25192 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,801 log 22076 22856 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:06:40,805 log 22076 7076 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,187 log 15484 19616 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,197 log 15484 24096 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,201 log 15484 21076 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,204 log 15484 24572 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,208 log 15484 25588 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,212 log 15484 21340 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,215 log 15484 7336 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,219 log 15484 25492 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,223 log 15484 19764 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,227 log 15484 22340 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,230 log 15484 21048 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,235 log 15484 25948 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:08:34,239 log 15484 25108 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 16:10:45,878 log 19188 25756 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 18:10:30,072 log 12520 26132 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 18:15:12,486 log 7844 18416 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 18:15:14,556 log 7844 24144 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 18:15:38,661 log 3172 8028 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 18:15:40,738 log 3172 17180 Internal Server Error: /accounts/api/register/
ERROR 2025-09-12 22:28:55,279 log 21516 16400 Internal Server Error: /api/reservations/relations/18/approve/
ERROR 2025-09-13 21:46:24,171 log 18948 4540 Internal Server Error: /api/reservations/bookings/my_schedule/
ERROR 2025-09-14 10:20:45,304 log 14624 18740 Internal Server Error: /api/reservations/bookings/26/cancel/
ERROR 2025-09-14 10:20:55,793 log 14624 18740 Internal Server Error: /api/reservations/bookings/27/cancel/
ERROR 2025-09-14 10:22:58,081 log 14624 18740 Internal Server Error: /api/reservations/bookings/28/cancel/
ERROR 2025-09-14 16:49:59,818 log 18456 2728 Internal Server Error: /payments/pending/
Traceback (most recent call last):
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\code\django_learning\keshe\payments\views.py", line 849, in pending_payments_list
    return render(request, 'payments/pending_payments.html', context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'payment_detail' not found. 'payment_detail' is not a valid view function or pattern name.
ERROR 2025-09-14 16:50:38,367 log 18456 2728 Internal Server Error: /payments/pending/
Traceback (most recent call last):
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\code\django_learning\keshe\payments\views.py", line 849, in pending_payments_list
    return render(request, 'payments/pending_payments.html', context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'payment_detail' not found. 'payment_detail' is not a valid view function or pattern name.
ERROR 2025-09-14 16:51:31,049 log 18456 2728 Internal Server Error: /payments/pending/
Traceback (most recent call last):
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\code\django_learning\keshe\payments\views.py", line 849, in pending_payments_list
    return render(request, 'payments/pending_payments.html', context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'payment_detail' not found. 'payment_detail' is not a valid view function or pattern name.
ERROR 2025-09-14 17:16:43,448 log 4912 12324 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\code\django_learning\keshe\keshe\admin_views.py", line 55, in admin_dashboard
    context['total_users'] = User.objects.count()
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\db\models\manager.py", line 196, in __get__
    raise AttributeError(
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'accounts.User'
ERROR 2025-09-14 17:16:46,528 log 4912 12324 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\code\django_learning\keshe\keshe\admin_views.py", line 55, in admin_dashboard
    context['total_users'] = User.objects.count()
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\db\models\manager.py", line 196, in __get__
    raise AttributeError(
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'accounts.User'
ERROR 2025-09-14 17:50:12,375 log 13436 5528 Internal Server Error: /admin/reservations/booking/add/
Traceback (most recent call last):
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\admin\options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\forms\models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\forms\models.py", line 321, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (payment_status) specified for Booking

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\admin\options.py", line 1782, in _changeform_view
    ModelForm = self.get_form(
  File "D:\Anaconda\envs\django_keshe\lib\site-packages\django\contrib\admin\options.py", line 811, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (payment_status) specified for Booking. Check fields/fieldsets/exclude attributes of class BookingAdmin.
